apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-k8scluster
spec:
  type: LoadBalancer
  selector:
    app: udacity-capstone-k8scluster
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-k8scluster-deploy
spec:
  selector:
    matchLabels:
      app: udacity-capstone-k8scluster
  replicas: 1
  template:
    metadata:
      labels:
        app: udacity-capstone-k8scluster
    spec:
      containers:
        - name: udacity-capstone-k8scluster-pod
          image: vaib79/udacity-capstone-k8scluster:0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10
